imdb/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from movie.views import HomeView

urlpatterns = [

    
    path('admin/', admin.site.urls),
    path('homepage/', include('movie.urls', namespace='movies'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie/urls.py
from django.urls import path
from .views import HomeView, MovieList , MovieDetail , MovieCategory , MovieLanguage , MovieSearch , MovieYear


app_name='movie'

urlpatterns = [
    path('', HomeView.as_view() , name='homepage'),
    path('movie_list', MovieList.as_view() , name='movie_list'),
    path('category/<str:category>', MovieCategory.as_view() , name='movie_category'),
    path('language/<str:lang>', MovieLanguage.as_view() , name='movie_language'),
    path('search/', MovieSearch.as_view() , name='movie_search'),
    path('<slug:slug>', MovieDetail.as_view() , name='movie_detail'),
    path('year/<int:year>', MovieYear.as_view() , name='movie_year'),
]

movie/models.py
from django.db import models
from django.utils.text import slugify
from django.utils import timezone
# Create your models here.

CATEGORY_CHOICES = (
    ('action','ACTION'),
    ('drama','DRAMA'),
    ('comedy','COMEDY'),
    ('romance','ROMANCE'),
)

LANGUAGE_CHOICES = (
    ('english' , 'ENGLISH'),
    ('german' , 'GERMAN'),
    ('japan', 'JAPAN'),
    ('korea', 'KOREA'),
    ('china','CHINA'),
)

STATUS_CHOICES = (
    ('RA' , 'RECENTLY ADDED'),
    ('MW' , 'MOST WATCHED'),
    ('TR' , 'TOP RATED'),
)

class Movie(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=1000)
    image = models.ImageField(upload_to='movies')
    banner = models.FileField(upload_to='movies_banner')
    category = models.CharField(choices=CATEGORY_CHOICES , max_length=10)
    language = models.CharField(choices=LANGUAGE_CHOICES , max_length=10)
    status = models.CharField(choices=STATUS_CHOICES , max_length=2)
    cast = models.CharField(max_length=100)
    year_of_production = models.DateField()
    views_count = models.IntegerField(default=0)
    movie_trailer = models.URLField()

    created = models.DateTimeField(default=timezone.now)

    slug = models.SlugField(blank=True, null=True)

    def save(self , *args , **kwargs):
        if not self.slug :
            self.slug = slugify(self.title)
        super(Movie , self).save( *args , **kwargs)

    def __str__(self):
        return self.title


 	# tags
 	# - download links
 	# - watch links

LINK_CHOICES = (
    ('D' , 'DOWNLOAD LINK'),
    ('W' , 'WATCH LINK'),
)


class MovieLinks(models.Model):
    movie = models.ForeignKey(Movie, related_name='movie_watch_link', on_delete=models.CASCADE)
    type = models.CharField(choices=LINK_CHOICES , max_length=1)
    link = models.URLField()

    def __str__(self):
        return str(self.movie)

movie/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView , DetailView
from django.views.generic.dates import YearArchiveView
from .models import Movie , MovieLinks






class HomeView(ListView):
    model = Movie
    template_name = 'movie/home.html'

    def get_context_data(self , **kwargs):
        context = super(HomeView , self).get_context_data(**kwargs)
        context['top_rated'] = Movie.objects.filter(status='TR')
        context['most_watched'] = Movie.objects.filter(status='MW')
        context['recently_added'] = Movie.objects.filter(status='RA') 
        return context


class MovieList(ListView):
    model = Movie
    paginate_by = 3


class MovieDetail(DetailView):
    model = Movie

    def get_object(self):
        object = super(MovieDetail , self).get_object()
        object.views_count += 1
        object.save()
        return object

    def get_context_data(self , **kwargs):
        context = super(MovieDetail , self).get_context_data(**kwargs)
        context['links'] = MovieLinks.objects.filter(movie=self.get_object())
        context['related_movies'] = Movie.objects.filter(category=self.get_object().category)#.order_by['created'][0:6]
        return context


class MovieCategory(ListView):
    model = Movie
    paginate_by = 3

    def get_queryset(self):
        self.category = self.kwargs['category']
        return Movie.objects.filter(category=self.category)

    def get_context_data(self , **kwargs):
        context = super(MovieCategory , self).get_context_data(**kwargs)
        context['movie_category'] = self.category
        return context



class MovieLanguage(ListView):
    model = Movie
    paginate_by = 2

    def get_queryset(self):
        self.language = self.kwargs['lang']
        return Movie.objects.filter(language=self.language)

    def get_context_data(self , **kwargs):
        context = super(MovieLanguage , self).get_context_data(**kwargs)
        context['movie_language'] = self.language
        return context


class MovieSearch(ListView):
    model = Movie
    paginate_by = 2

    def get_queryset(self):
        query = self.request.GET.get('query')
        if query:
            object_list = self.model.objects.filter(title__icontains=query)
        
        else:
            object_list = self.model.objects.none()

        return object_list

class MovieYear(YearArchiveView):
    model=Movie
    paginate_by=2
    queryset = Movie.objects.all()
    date_field = 'year_of_production'
    make_object_list = True
    allow_future = True
    allow_empty=True

    print(queryset)
        

movie/templates/movie/home.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<!--Recently Added-->>
<section id="iq-favorites">
	<div class="container-fluid">
	  <div class="row">
		<div class="col-sm-12 overflow-hidden">
		  <div class="iq-main-header d-flex align-items-center justify-content-between">
			<h4 class="main-title">Recently Added</h4>
			{% comment %} <a href="#" class="iq-view-all">View All</a> {% endcomment %}
		  </div>
		  <div class="favorite-contens">
			
			 <ul class="favorites-slider list-inline row p-0 mb-0">
			{% for movie in recently_added %} 	
			 <li class="slide-item">
				    <div id="videosList">           

					  <div class="video">
						<video width="270px" height="240px" class="thevideo" loop preload>
						  <source src="{{movie.banner.url}}" >
						 
						</video>
					  </div>
					  
					</div>
				
                    <div class="block-description">
                      <h6 class="iq-title">
                        <a href="#"> {{movie.title}} </a>
                      </h6>
                      <div class="movie-time d-flex align-items-center my-2">
                        <div class="badge badge-secondary p-1 mr-2">10+</div>
                        <span class="text-white">{{movie.views_count}} views</span>
                      </div>
                      <div class="hover-buttons">
                        <span class="btn btn-hover iq-button">
                          <i class="fa fa-play mr-1"></i>
                             <a href="{% url 'movies:movie_detail' movie.slug %}">Play Now</a>
                        </span>
                      </div>
                    </div>
				
			 </li>
			{% endfor %}
			 </ul>
		    	
		  </div>
		</div>
	  </div>
	</div>
  </section>

<!--Most Watched slide-->
<section id="iq-favorites">
	<div class="container-fluid">
	  <div class="row">
		<div class="col-sm-12 overflow-hidden">
		  <div class="iq-main-header d-flex align-items-center justify-content-between">
			<h4 class="main-title">Most Watched</h4>
			{% comment %} <a href="#" class="iq-view-all">View All</a> {% endcomment %}
		  </div>
		  <div class="favorite-contens">
			
			 <ul class="favorites-slider list-inline row p-0 mb-0">
			{% for movie in most_watched %} 	
			 <li class="slide-item">
				    <div id="videosList">           

					  <div class="video">
						<video width="270px" height="240px" class="thevideo" loop preload>
						  <source src="{{movie.banner.url}}" >
						 
						</video>
					  </div>
					  
					</div>
				
                    <div class="block-description">
                      <h6 class="iq-title">
                        <a href="#"> {{movie.title}} </a>
                      </h6>
                      <div class="movie-time d-flex align-items-center my-2">
                        <div class="badge badge-secondary p-1 mr-2">10+</div>
                        <span class="text-white">{{movie.views_count}} views</span>
                      </div>
                      <div class="hover-buttons">
                        <span class="btn btn-hover iq-button">
                          <i class="fa fa-play mr-1"></i>
                             <a href="{% url 'movies:movie_detail' movie.slug %}">Play Now</a>
                        </span>
                      </div>
                    </div>
				
			 </li>
			{% endfor %}
			 </ul>
		    	
		  </div>
		</div>
	  </div>
	</div>
  </section>


<!--Top rated slide-->
<section id="iq-favorites">
	<div class="container-fluid">
	  <div class="row">
		<div class="col-sm-12 overflow-hidden">
		  <div class="iq-main-header d-flex align-items-center justify-content-between">
			<h4 class="main-title">Top rated</h4>
			{% comment %} <a href="#" class="iq-view-all">View All</a> {% endcomment %}
		  </div>
		  <div class="favorite-contens">
			
			 <ul class="favorites-slider list-inline row p-0 mb-0">
			{% for movie in top_rated %} 	
			 <li class="slide-item">
				    <div id="videosList">           

					  <div class="video">
						<video width="270px" height="240px" class="thevideo" loop preload>
						  <source src="{{movie.banner.url}}" >
						 
						</video>
					  </div>
					  
					</div>
				
                    <div class="block-description">
                      <h6 class="iq-title">
                        <a href="#"> {{movie.title}} </a>
                      </h6>
                      <div class="movie-time d-flex align-items-center my-2">
                        <div class="badge badge-secondary p-1 mr-2">10+</div>
                        <span class="text-white">{{movie.views_count}} views</span>
                      </div>
                      <div class="hover-buttons">
                        <span class="btn btn-hover iq-button">
                          <i class="fa fa-play mr-1"></i>
                             <a href="{% url 'movies:movie_detail' movie.slug %}">Play Now</a>
                        </span>
                      </div>
                    </div>
				
			 </li>
			{% endfor %}
			 </ul>
		    	
		  </div>
		</div>
	  </div>
	</div>
</section>



{% endblock body %}
		 




             

movie/templates/movie/movie_archive_year.html
{% extends 'base.html' %}
{% block body %}
<div id="site-content">
    <main class="main-content">
        <div class="container">
            <div class="page">
                
                <div class="filters">
                    <select name="#" id="#" placeholder="Choose Category">
                        <option value="#">
                            {% if year %}
                             <h3>Movies release in {{year|date:"Y"}} </h3>
                            {% endif %}
                            
                            
                        </option>
                        
                    </select>
                   
                </div>
                <div class="movie-list ">
                  {% for movie in object_list %}
                    <div class="movie mydisabled">
                        <figure class="movie-poster"><img src="{{movie.image.url}}" alt="#"></figure>
                        
                    </div>
                    <div class="movie ">
                        
                        <div class="movie-title"><a href="{% url 'movies:movie_detail' movie.slug %}">{{movie.title}}</a></div>
                        <p>{{movie.description}}</p>
                    </div>
                    {% empty %}
                    <h3>There Are No Movies In This Category</h3></br>
                  {% endfor %}
                </div> <!-- .movie-list -->

                <div class="pagination">
                                       
                            {% if page_obj.has_previous %}
                                <li><a href="?page={{ page_obj.previous_page_number }}" class="page-number prev"><i class="fa fa-angle-left"></i>Prev</a></li>
                            {% else %}
                                <li class="disabled"></li>
                            {% endif %}
                            
                            {% for pages in page_obj.paginator.page_range %}
                              {% if page_obj.number == pages %}
                                <li><a href="#" class="page-number">{{pages}}</a></li>
                              {% else %}
                                <li><a href="?page={{pages}}" class="page-number">{{pages}}</a></li>
                              {% endif %}
                            {% endfor %}

                            {% if page_obj.has_next %}
                                <li><a href="?page={{ page_obj.next_page_number }}" class="page-number next"><i class="fa fa-angle-right" ></i>Next</a></li>
                            {% else %}
                                <li class="disabled"></li>
                            {% endif %}
                </div>
            </div>
        </div> <!-- .container -->
    </main>
			
 </div>
{% endblock body %}

movie/templates/movie/movie_detail.html
{% extends 'base.html' %}
{% block body %}


<section id="headbox1" >
		  
	
	 
		{% comment %} <div class="home-slider slick-bg">
			<iframe id="myVideo" width="560" height="315" src="{{object.movie_trailer}}" frameborder="0" allowfullscreen></iframe>
			
		</div> {% endcomment %}
	  
		<div class="box text-center" dir="ltr">
    
			<div class="neo-video-player" id="popout-video-player">
		
				<div class="video-control-part">
					<div class="video-control-general-part">
						<div class="play-btn video-neu-btn"></div>
						<div class="video-neu-btn drop-btn">
							<div class="box-sound">
								<div class="volume">
									<div class="bar-volume"></div>
								</div>
							</div>
							<div class="sound-btn video-neu-btn"></div>
						</div>
					</div>
					<div class="video-control-bar-part">
						<div class="bar-bg">
							<div class="bar-progress">
								<div class="bar-time">
									<div class="bar-time-box"><span class="current">00:00</span><span> / </span><span class="duration">00:00</span></div>
									<div class="bar-pin"></div>
								</div>
							</div>
							<div class="bar-buffer"></div>
						</div>
					</div>
					<div class="video-control-nav-part">
						<a id="download-video" href=""  rel="nofollow" download><div class="download-btn video-neu-btn"></div></a>
						<div class="setting-btn video-neu-btn">
							<div class="fastFwd-box">
								<input class="btn fastFwd" type="button" value="Speed : 1x">
							</div>
						</div>
						<div class="fullscreen-btn video-neu-btn"></div>
					</div>
				</div>
				
				<video class="video-element" id="video-element" preload="auto" >
				   <source src="{{object.banner.url}}">
				<video>
				
			</div>
		
		</div> 		
	 
	
  
</section>
 
<section id="parallex" class="parallax-window">
	<div class="container-fluid h-100">
	  <div class="row align-items-center justify-content-center h-100 parallaxt-details">
		<div class="col-lg-4 r-mb-23">
		  <div class="text-left">
			<a href="javascript:void(0)">
			  <h1 class="parallax-heading">{{object.title}}</h1>
			</a>
			<div class="parallax-ratting d-flex align-items-center mt-3 mb-3">
			 
			  <span class="text-white ml-3">{{object.views_count}} Views</span>
			</div>
			<div class="movie-time d-flex align-items-center mb-3">
			  <div class="badge badge-secondary p-1 mr-2"></div>
			  <span class="text-white">Release: {{object.year_of_production}} </span>
			</div>
			<p>
				{{object.description}}
			</p>
			<div class="parallax-buttons">
			  <a href="#" class="btn btn-hover">Play Now</a>
			  
			</div>
						
			<a href="https://www.facebook.com/sharer/sharer.php?u={% url 'movies:movie_detail' movie.slug %}" target="_blank">
				Share on Facebook
			  </a>
		  </div>
		</div>
		<div class="col-lg-8">
		  <div class="parallax-img">
			<a href="#"><img src="{{object.image.url}}" alt="" class="img-fluid w-100" /></a>
		  </div>
		</div>
	  </div>
	</div>
  </section>

  <section id="iq-favorites">
	<div class="container-fluid">
	  <div class="row">
		<div class="col-sm-12 overflow-hidden">
		  <div class="iq-main-header d-flex align-items-center justify-content-between">
			<h4 class="main-title">Related Movies</h4>
			{% comment %} <a href="#" class="iq-view-all">View All</a> {% endcomment %}
		  </div>
		  <div class="favorite-contens">
			
			 <ul class="favorites-slider list-inline row p-0 mb-0">
			{% for movie in related_movies %} 	
			 <li class="slide-item">
				    <div id="videosList">           

					  <div class="video">
						<video width="270px" height="240px" class="thevideo" loop preload>
						  <source src="{{movie.banner.url}}" >
						 
						</video>
					  </div>
					  
					</div>
				
                    <div class="block-description">
                      <h6 class="iq-title">
                        <a href="#"> {{movie.title}} </a>
                      </h6>
                      <div class="movie-time d-flex align-items-center my-2">
                        <div class="badge badge-secondary p-1 mr-2"></div>
                        <span class="text-white">{{movie.views_count}} views</span>
                      </div>
                      <div class="hover-buttons">
                        <span class="btn btn-hover iq-button">
                          <i class="fa fa-play mr-1"></i>
                             <a href="{% url 'movies:movie_detail' movie.slug %}">Play Now</a>
                        </span>
                      </div>
                    </div>
				
			 </li>
			{% endfor %}
			 </ul>
		    	
		  </div>
		</div>
	  </div>
	</div>
  </section>

			
	

{% endblock body %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Movies</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">

	<!-- Link CSS -->
	
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Alfa+Slab+One">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oswald">
    

	<link rel="stylesheet" href="{% static 'css/slick.css' %}">
	<link rel="stylesheet" href="{% static 'css/slick-theme.css' %}" >
	<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/animate.min.css' %}" >
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
	<link rel="stylesheet" href="{% static 'css/select2.min.css' %}" >
	<link rel="stylesheet" href="{% static 'css/select2-bootstrap4.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/slick-animation.css' %}">
	<link rel="stylesheet" href="{% static 'css/style2.css' %}">
    <link rel="stylesheet" href="{% static 'swiper.css' %}">
	<link rel="stylesheet" href="{% static 'style.css' %}">



</head>

<body>
    
		<header id="main-header">
			<div class="main-header">
				<div class="container-fluid">
					<div class="row">
						<div class="col-sm-12">
						  <nav class="navbar navbar-expand-lg navbar-light p-0">
							<a href="#" class="navbar-toggler c-toggler" data-toggle="collapse" data-target="#navbarSupportedContent"
							  aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
							  <div class="navbar-toggler-icon" data-toggle="collapse">
								<span class="navbar-menu-icon navbar-menu-icon--top"></span>
								<span class="navbar-menu-icon navbar-menu-icon--middle"></span>
								<span class="navbar-menu-icon navbar-menu-icon--bottom"></span>
							  </div>
							</a>
							<a href="index.html" class="navbar-brand">
								<img src="images/logo.png" class="img-fluid logo" alt="" />
							  </a>
							  <div class="collapse navbar-collapse" id="navbarSupportedContent">
								<div class="menu-main-menu-container">
								  <ul id="top-menu" class="navbar-nav ml-auto">
									<li class="menu-item"><a href="{% url 'movie:homepage'%}">Home</a></li>
									<li class="menu-item">
										<a href="#">Genres</a>
										<ul class="sub-menu">
										  <li class="menu-item"><a href="{% url 'movies:movie_category' 'action' %}">Action</a></li>
										  <li class="menu-item"><a href="{% url 'movies:movie_category' 'comedy' %}">Comedy</a></li>
										  <li class="menu-item"><a href="{% url 'movies:movie_category' 'drama' %}">Drama</a></li>
										  <li class="menu-item"><a href="{% url 'movies:movie_category' 'romance' %}">Romance</a></li>
										</ul>
									</li>	
									<li class="menu-item">
										<a href="#">Year</a>
										<ul class="sub-menu">
										  <li class="menu-item"><a href="{% url 'movies:movie_year' year=2019 %}">2019</a></li>
										  <li class="menu-item"><a href="{% url 'movies:movie_year' year=2018 %}">2018</a></li>
										  <li class="menu-item"><a href="{% url 'movies:movie_year' year=2017 %}">2017</a></li>
										  <li class="menu-item"><a href="{% url 'movies:movie_year' year=2016 %}">2016</a></li>
										</ul>
									</li>	
									<li class="menu-item">
										<a href="#">Language</a>
										<ul class="sub-menu">
										   <li class="menu-item"><a href="{% url 'movies:movie_language' 'english' %}">English</a></li>
										   <li class="menu-item"><a href="{% url 'movies:movie_language' 'german' %}">German</a></li>
										   <li class="menu-item"><a href="{% url 'movies:movie_language' 'korea' %}">Korea</a></li>
										   <li class="menu-item"><a href="{% url 'movies:movie_language' 'japan' %}">Japan</a></li>
										   <li class="menu-item"><a href="{% url 'movies:movie_language' 'china' %}">China</a></li>
										</ul>
									</li>
								  </ul>
								</div>
							  </div>	
							  <div class="mobile-more-menu">
								<a href="javascript:void(0);" class="more-toggle" id="dropdownMenuButton" data-toggle="more-toggle"
								  aria-haspopup="true" aria-expanded="false">
								  <i class="fa fa-ellipsis-h"></i>
								</a>
								<div class="more-menu" aria-labelledby="dropdownMenuButton">
								  <div class="navbar-right position-relative">
									<ul class="d-flex align-items-center justify-content-end list-inline m-0">
									  <li>
										<a href="#" class="search-toggle">
										  <i class="fa fa-search"></i>
										</a>
										<div class="search-box iq-search-bar">
											<form action="{% url 'movies:movie_search' %}" class="searchbox" method="GET">
											  <div class="form-group position-relative">
												<input type="text" name="query" value="{{request.GET.q}}" class="text search-input font-size-12"
												  placeholder="type here to search..." />
												<i class="search-link fa fa-search"></i>
											  </div>
											</form>
										  
										  </div>
									  </li>
									  <li class="nav-item nav-icon">
										<a href="#" class="iq-user-dropdown search-toggle d-flex align-items-center p-0">
										  Login
										</a>
										
									  </li>
									</ul>
								  </div>
								</div>
							  </div>
							  <div class="navbar-right menu-right">
								<ul class="d-flex align-items-center list-inline m-0">
								  <li class="nav-item nav-icon">
									<a href="#" class="search-toggle device-search">
									  <i class="fa fa-search"></i>
									</a>
									<div class="search-box iq-search-bar d-search">
									  <form action="{% url 'movies:movie_search' %}" class="searchbox">
										<div class="form-group position-relative">
										  <input type="text" class="text search-input font-size-12" name="query" value="{{request.GET.q}}" 
											placeholder="type here to search..." />
										  <i class="search-link fa fa-search"></i>
										</div>
									  </form>
									</div>
								  </li>
								
								  <li class="nav-item nav-icon">
									<a href="#" class="iq-user-dropdown search-toggle d-flex align-items-center p-0">
									  Login
									</a>
									
								  </li>
								</ul>
							  </div>
							</nav>
							<div class="nav-overlay"></div>
						  </div>
						</div>
					  </div>
					</div>
				  </header>
				
		
		<!-- Slider -->
		
		<section id="home" class="iq-main-slider p-0">
		  
			<div id="home-slider" class="slider m-0 p-0">
			 {% for movie in recently_added %} 
				<div class="home-slider slick-bg">
					{% if movie.banner %}
							<video id="video_background" preload="auto" autoplay="true" loop="loop" muted volume="0">
								<source  src="{{movie.banner.url}}">
							</video>
					{% endif %}
					<div class="container-fluid position-relative h-100">
					<div class="slider-inner h-100">						
						<div class="row align-items-center h--100">
						<div class="col-xl-6 col-lg-12 col-md-12">					
							
							
							<h1 class="slider-text big-title title text-uppercase" data-animation-in="fadeInLeft"
							data-delay-in="0.6">
							{{movie.title}}
							</h1>
							
							<div class="d-flex flex-wrap align-items-center fadeInLeft animated" data-animation-in="fadeInLeft"
							style="opacity: 1">
														
							</div>
							<p data-animation-in="fadeInUp">
								{{movie.description}}
							</p>
							<div class="trending-list" data-animation-in="fadeInUp" data-delay-in="1.2">
							<div class="text-primary title starring">
								Cast :
								<span class="text-body">{{movie.cast}}</span>
							</div>
							<div class="text-primary title genres">
								Genres : <span class="text-body">{{movie.category}}</span>
							</div>
							<div class="text-primary title year">
								Year of production :
								<span class="text-body">{{movie.year_of_production}}</span>
							</div>
							</div>
							<div class="d-flex align-items-center r-mb-23 mt-4" data-animation-in="fadeInUp" data-delay-in="1.2">
							<a href="{% url 'movies:movie_detail' movie.slug %}" class="btn btn-hover iq-button"><i class="fa fa-play mr-3"></i>Play Now</a>
							
							</div>
							
						</div>
						
						</div>
					
					</div>
					</div>
					
				</div>
			  {% endfor %}
			</div>
		  
		</section>
		{% block body %}
		  
		{% endblock body %}	
		
        
		<footer class="iq-bg-dark">
			<div class="footer-top">
			<div class="container-fluid">
				<div class="row footer-standard">
				<div class="col-lg-5">
					<div class="widget text-left">
					<div>
						<ul class="menu p-0">
						<li><a href="{% url 'movie:homepage'%}">Home</a></li>
						<li><a href="#">Privacy-Policy</a></li>
						<li><a href="#">FAQ</a></li>
						<li><a href="#">Watch List</a></li>
						</ul>
					</div>
					</div>
					<div class="widget text-left">
					<div class="textwidget">
						<p><small>
							<li>Watch Free Movies</li>
							<li>English Subtitled Movies</li>
							<li>Latest Movies Trailers</li>
							<li>New Movies Trailers</li></small></p>
					</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 mt-4 mt-lg-0">
					<h6 class="footer-link-title">
					Follow Us:
					</h6>
					<ul class="info-share">
					<li>
						<a href="#">
						<i>
						<fa class="fa fa-facebook"></fa>
						</a>
					</li>
					<li>
						<a href="#">
						<i>
						<fa class="fa fa-youtube"></fa>
						</a>
					</li>
					<li>
						<a href="#">
						<i>
						<fa class="fa fa-instagram"></fa>
						</a>
					</li>
					</ul>
				</div>
				
				</div>
			</div>
			</div>
		</footer>
		
	{% block content %}
		
	{% endblock content %}
     
	
  	<!-- Link JS-->>
	<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
	<script src="{% static 'js/popper.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/slick.min.js' %}"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'js/select2.min.js' %}"></script>
	<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'js/slick-animation.min.js' %}"></script>
	<script src="{% static 'js/hovervid.js' %}"></script>
	<script src="{% static 'js/videoplayer.js' %}"></script>
    <script src="{% static 'main.js' %}"></script>
	
	
</body>
</html>